#ifndef HIGH_PERF_SOFTWARE_SRC_TASK2_GENERATE_ARRAY_GENERATE_ARRAY_HPP_
#define HIGH_PERF_SOFTWARE_SRC_TASK2_GENERATE_ARRAY_GENERATE_ARRAY_HPP_

#include <cstddef>

int* generateArray(const std::size_t size, const int max);

#endif  // HIGH_PERF_SOFTWARE_SRC_CS_TASK2_GENERATE_ARRAY_GENERATE_ARRAY_HPP_
